### ISSUE TITLE
Anonymous Messages to Rooms

### ISSUE THREAD

**Issue by ataylor32** [RidleyLarsen/hip-chatbot#10]
I am creating this issue on behalf of Mark. He would like to be able to post a message to a room anonymously, much like the issue #7's feature, but with the ability to say anything. So the chatbot could post a message like this to one of the rooms:

> From anonymous: The small conference room was clean this morning but it's looking pretty messy now. It would be great if whoever is responsible would clean it up.

**Comment by RidleyLarsen** [comment]
I don't like it. It could be abused. That is not a good example because I don't see a reason why he couldn't say that himself.
