### ISSUE TITLE
Crash on @tp

### ISSUE THREAD

**Issue by RidleyLarsen** [RidleyLarsen/hip-chatbot#11]
See Title

**Comment by joshbeitler** [comment]
Isn't this because your checker is down?

**Comment by RidleyLarsen** [comment]
Eh? I don't understand what you mean by that.

**Comment by joshbeitler** [comment]
I think it is/was only crashing due to not being able to reach the Pi.

**Comment by RidleyLarsen** [comment]
Oh, yeah, that was right.
