### ISSUE TITLE
Jimmy John's Ordering

### ISSUE THREAD

**Issue by RidleyLarsen** [RidleyLarsen/hip-chatbot#8]
Integrate JJXP: Jimmy John's over XMPP Protocol
Possible format:
!jj 3 -pickle -tomato -mayo
!jj 3 +slim +beef
https://www.npmjs.com/package/makemeasandwich (???)

**Comment by freakypie** [comment]
this must be done
for the sake of us all

**Comment by RidleyLarsen** [comment]
jimmy john's won't deliver to us, no matter how you format the address. :-1:
